
* Começando

 Vamos aprender a usar as funções do 3.3, já que ele que começa a largar a mão do modo imediato (ou de função fixa). E que toda e qualquer versão mais moderna acaba usando as mesmas funções e mais algumas especializadas.

 A versão mais nova (agora que estou escrevendo) é a 4.6.

 Já que não me preocupei com instalar o pacote de HSLS, vamos ter blocos de código em C++ para o tutorial todo.

#+begin_src C++
  if(GL_ARB_extension_name)
    {
      // Código para a extensão
    }
   else
     {
       // Código sem a extensão
     }
#+end_src

 A título de exemplo, você pode adicionar isso para os /shaders/, que usam ou não funções mais novas. Pense em diretrizes de compilação de um compilador.

** A máquina de estados

 O modelo de computação é de ficar alterando uma máquina de estados e tomar algumas ações nesse estado. Chamamos o estado de contexto.

 Nós mutamos o estado ao estilo C:
 
#+begin_src c++
  // Criação do objeto
  unsigned int objectId = 0;
  glGenObject(1, &objectId);

  // Atribuição do objeto ao contexto
  glBindObject(GL_WINDOW_TARGET, objectId);

  // Configuramos opções do objeto
  glSetObjectOption(GL_WINDOW_TARGET, GL_OPTION_WINDOW_WIDTH, 800);
  glSetObjectOption(GL_WINDOW_TARGET, GL_OPTION_WINDOW_HEIGHT, 600);

  // Voltando o contexto ao padrão
  glBindObject(GL_WINDOW_TARGET, 0);
#+end_src

 Percerba que a atribuição é por meio de funções (quasi construtores e /setters/getters/ de OOP). Importante também é como o objeto ganha um identificador numérico. Se eu lembro corretamente, é por causa que o identificador é melhor para tratar em um ambiente de computação heterogênea, ao invés de uma variável normal, pelo /layout/ de memória ser diferente entre os dois equipamentos. Pense em duas bibliotecas que precisam emprestar livros entre si, que se uma usar a posição de prateleira, não funciona, mas se usar o ISBN, é fácil de encontrar, mesmo estando em posições diferentes.

 Um padrão de programação comum é esse do código:
 1) Criamos um identificador;
 2) Atribuimos um objeto ao identificador;
 3) Configuramos esse objeto;
 4) Liberamos o objeto ao jogar ele no identificador zero.

* Criando uma janela

** GLFW

 Bastante coisa varia por sistema operacional, então vamos ter que pedir ajuda de uma biblioteca. No caso, vão usar o GLFW e a (porcaria) do MSVS 2019.

 Já temos para Nix a biblioteca, assim como para Ubuntu os binários. Também copiamos os ~includes~ para podermos desenvolver.

 Eles sugerem usar o CMake, mas já que o tutorial não só é para Windows, como também usa a configuração gráfica, é literalmente inútil para a gente. Obrigado por absolutamente nada.

 Eles fazem a palhaçada também de fazer apenas as coisas específicas do Visual Studio, como a merda da solução.

 De maneira geral, eles sugerem usar o src_c{#include <GLFW/glfw3.h>} e as opções de compilação ~-glfw3 -lGL -lX11 lpthread -lXrandr -lXi -ldl~. Claro que estamos vivendo no passado com X11. Eu odeio tudo isso.

** GLAD

 Eles pedem para que seja o /binding/ para C++ e o GLAD1.

 E já que o /setup/ é bem confuso pra Windows, mas mais simples para Linux, vamos seguir o tutorial recomendado aqui: [[https://medium.com/geekculture/a-beginners-guide-to-setup-opengl-in-linux-debian-2bfe02ccd1e][A Beginner’s Guide to Setup OpenGL in Linux (Debian)]]. Ele é meio que parecido para Ubuntu, mas já que, nesse exato momento, estou no NixOS, vou colocar um ~flake.nix~ aqui para nos ajudar.

 Fiz algumas coisas aqui na pasta, como um CMakeLists, já que a gente tem que fazer na mão, assim como o flake.nix.

 Eles não devem estar perfeitos, mas a gente vai ajustando de acordo com a necessidade.

* Hello Window

 Vamos fazer aqui um negócio para conseguir costurar tudo. Sim, vamos fazer isso de maneira literária.

 Ignore, por enquanto, os <<noweb>>

#+begin_src C++ :tangle ./hello_window.cpp :noweb yes
  #include <glad/glad.h>
  #include <GLFW/glfw3.h>
  #include <iostream>
  <<includes_plus>>

  <<declaration_resize_callback>>
  <<escape_window_declaration>>

  int main ()
  {
    glfwInit();
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    // glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE); <- Caso fosse MacOS

    <<window_options>>

    <<init_glad>>

    <<gl_viewport>>

    <<window_resize_callback_registration>>

    <<close_loop>>

    <<glfw_terminate>>
    
    return 0;
  }

  <<definition_resize_callback>>

#+end_src

 Nessa parte, configuramos o GLFW (para não termos que fazer isso na mão) com cada uma das opções (e deve ser um enum) e o valor da opção.

 Nesse caso, damos para ele a versão mais simples do OpenGL que falamos lá em cima, a 3.3.

#+name: window_options
#+begin_src C++ 
  GLFWwindow* window = glfwCreateWindow(800, 600, "LearnOpenGL", NULL, NULL);

  std::cout << "Creating window..." << std::endl; // Para termos um feedback

  if (window == NULL)
    {
      std::cout << "Failed to create GLFW window" << std::endl;
      glfwTerminate();
      return -1;
    }
  glfwMakeContextCurrent(window);
#+end_src

 Com uma largura e altura, respectivamente, e o nome, criamos a janela. Já que ela ainda não tem uma lógica de aguardar, então ela surge por um micro segundo e some, por isso damos um aviso no console.

 Precisamos inicializar o GLAD também, já que vamos usar ele para gerenciar ponteiros de funções.

#+name: init_glad
#+begin_src C++
  if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress))
    {
    std::cout << "Failed to initialize GLAD" << std::endl;
      return -1;
    }
#+end_src

 Para gerenciar o tamanho da tela (virtual, o /view port/), temos esse código aqui:

#+name: gl_viewport
#+begin_src C++
  glViewport(0, 0, 800, 600);
#+end_src

 É interessante que isso é o espaço que o OpenGL vai tomar da janela, então poderíamos dar para ele uma tela menor e fazer com que coisas apareçam na janela.

 Também há uma questão de que o OpenGL nos dá um jeito de fazer referência meio estranha, com o 0,0 sendo o meio da tela, com -1 mais a esquerda, e/ou mais a cima.

 Lembremos que é o sistema de coordenadas de tela.

 E caso queiramos ter uma janela que responde com o usuário mexendo nas dimensões dela, usamos isso aqui:

#+name: declaration_resize_callback
#+begin_src C++
  void framebuffer_size_callback(GLFWwindow* window, int width, int height);
#+end_src

 com a immplementação ficando:

#+name: definition_resize_callback
#+begin_src C++
  void framebuffer_size_callback(GLFWwindow* window, int width, int height)
  {
    glViewport(0, 0, width, height);
  }
#+end_src

 Agora, vai ser meio estranho, já que registramos o /callback/, mas não passamos argumentos para ele. Isso acontece pelo GLFW fazer isso pra gente:

#+name: window_resize_callback_registration
#+begin_src C++
  glfwSetFramebufferSizeCallback(window, framebuffer_size_callback);
#+end_src

 Finalmente, vamos colocar um /loop/ para ver se deve ou não fechar a janela:

#+name: close_loop
#+begin_src C++ :noweb yes
  while(!glfwWindowShouldClose(window))
    {
      <<escape_window_call>>

      <<cleaning_color_plus>>
        
      glfwSwapBuffers(window);
      glfwPollEvents();
    }
#+end_src

 Preste atenção que usamos o modelo de /double buffering/. Lembre-se: o da frente é a superfície de exibição, o de trás é onde o programa escreve.

 E, por fim, precisamos limpar a bagunça:

#+name: glfw_terminate
#+begin_src C++
  glfwTerminate();
#+end_src

 Queremos colocar um pouco de resposta a entradas no nosso programa, como, ao apertar ESC, fechar o programa:

#+name: escape_window_declaration
#+begin_src C++
  void processInput(GLFWwindow *window)
  {
    if(glfwGetKey(window, GLFW_KEY_ESCAPE) == GLFW_PRESS)
      glfwSetWindowShouldClose(window, true);
  }
#+end_src

#+name: escape_window_call
#+begin_src C++
  processInput(window);
#+end_src

 Aqui, eles falam que "o /render loop/ também é chamado de frame", mas eu nunca vi alguém além deles chamarem isso assim. Que seja, não seria a primeira vez deles fazendo besteira.

 Mas uma coisa que é legal é esse negócio aqui, que dá uma cor para a tela, mostrando que ela está se limpando:

#+name: cleaning_color
#+begin_src C++
  glClearColor(0.2f, 0.3f, 0.3f, 1.0f);
  glClear(GL_COLOR_BUFFER_BIT);
#+end_src

 E eles chamam a primeira função de /state setting/, com a segunda sendo /state using/. O que é bem maneiro, ter a distinção e o vocabulário.

 E por termos acabado, vamos fazer uma bagunça: e se as cores de limpeza mudarem com o tempo?

#+name: includes_plus
#+begin_src C++
  #include <cmath>
  #include <chrono>

  // e vamos fazer uma sujeirinha aqui:

  auto beginning_app = std::chrono::high_resolution_clock::now();
#+end_src

 E, então, vamos usar cosseno e tempo para brincar:

#+name: cleaning_color_plus
#+begin_src C++
  auto r = std::cosf(std::chrono::duration<float>(std::chrono::high_resolution_clock::now() - beginning_app).count()) + 1.0f;
  auto g = std::cosf(std::chrono::duration<float>(std::chrono::high_resolution_clock::now() - beginning_app).count()) + 1.0f;
  auto b = std::cosf(std::chrono::duration<float>(std::chrono::high_resolution_clock::now() - beginning_app).count()) + 1.0f;

  glClearColor(r, g, b, 1.0f);
  glClear(GL_COLOR_BUFFER_BIT);
#+end_src

Bem, eu acho que por termos perda de precisão, não varia tanto assim, mas que seja, ela pisca!

* 
