
* Começando

 Vamos aprender a usar as funções do 3.3, já que ele que começa a largar a mão do modo imediato (ou de função fixa). E que toda e qualquer versão mais moderna acaba usando as mesmas funções e mais algumas especializadas.

 A versão mais nova (agora que estou escrevendo) é a 4.6.

 Já que não me preocupei com instalar o pacote de HSLS, vamos ter blocos de código em C++ para o tutorial todo.

#+begin_src C++
  if(GL_ARB_extension_name)
    {
      // Código para a extensão
    }
   else
     {
       // Código sem a extensão
     }
#+end_src

 A título de exemplo, você pode adicionar isso para os /shaders/, que usam ou não funções mais novas. Pense em diretrizes de compilação de um compilador.

** A máquina de estados

 O modelo de computação é de ficar alterando uma máquina de estados e tomar algumas ações nesse estado. Chamamos o estado de contexto.

 Nós mutamos o estado ao estilo C:
 
#+begin_src c++
  // Criação do objeto
  unsigned int objectId = 0;
  glGenObject(1, &objectId);

  // Atribuição do objeto ao contexto
  glBindObject(GL_WINDOW_TARGET, objectId);

  // Configuramos opções do objeto
  glSetObjectOption(GL_WINDOW_TARGET, GL_OPTION_WINDOW_WIDTH, 800);
  glSetObjectOption(GL_WINDOW_TARGET, GL_OPTION_WINDOW_HEIGHT, 600);

  // Voltando o contexto ao padrão
  glBindObject(GL_WINDOW_TARGET, 0);
#+end_src

 Percerba que a atribuição é por meio de funções (quasi construtores e /setters/getters/ de OOP). Importante também é como o objeto ganha um identificador numérico. Se eu lembro corretamente, é por causa que o identificador é melhor para tratar em um ambiente de computação heterogênea, ao invés de uma variável normal, pelo /layout/ de memória ser diferente entre os dois equipamentos. Pense em duas bibliotecas que precisam emprestar livros entre si, que se uma usar a posição de prateleira, não funciona, mas se usar o ISBN, é fácil de encontrar, mesmo estando em posições diferentes.

 Um padrão de programação comum é esse do código:
 1) Criamos um identificador;
 2) Atribuimos um objeto ao identificador;
 3) Configuramos esse objeto;
 4) Liberamos o objeto ao jogar ele no identificador zero.

* Criando uma janela

** GLFW

 Bastante coisa varia por sistema operacional, então vamos ter que pedir ajuda de uma biblioteca. No caso, vão usar o GLFW e a (porcaria) do MSVS 2019.

 Já temos para Nix a biblioteca, assim como para Ubuntu os binários. Também copiamos os ~includes~ para podermos desenvolver.

 Eles sugerem usar o CMake, mas já que o tutorial não só é para Windows, como também usa a configuração gráfica, é literalmente inútil para a gente. Obrigado por absolutamente nada.

 Eles fazem a palhaçada também de fazer apenas as coisas específicas do Visual Studio, como a merda da solução.

 De maneira geral, eles sugerem usar o src_c{#include <GLFW/glfw3.h>} e as opções de compilação ~-glfw3 -lGL -lX11 lpthread -lXrandr -lXi -ldl~. Claro que estamos vivendo no passado com X11. Eu odeio tudo isso.

** GLAD

 Eles pedem para que seja o /binding/ para C++ e o GLAD1.

 E já que o /setup/ é bem confuso pra Windows, mas mais simples para Linux, vamos seguir o tutorial recomendado aqui: [[https://medium.com/geekculture/a-beginners-guide-to-setup-opengl-in-linux-debian-2bfe02ccd1e][A Beginner’s Guide to Setup OpenGL in Linux (Debian)]]. Ele é meio que parecido para Ubuntu, mas já que, nesse exato momento, estou no NixOS, vou colocar um ~flake.nix~ aqui para nos ajudar.

 Fiz algumas coisas aqui na pasta, como um CMakeLists, já que a gente tem que fazer na mão, assim como o flake.nix.

 Eles não devem estar perfeitos, mas a gente vai ajustando de acordo com a necessidade.

* Hello Window

 Vamos fazer aqui um negócio para conseguir costurar tudo. Sim, vamos fazer isso de maneira literária.

 Ignore, por enquanto, os <<noweb>>

#+begin_src C++ :tangle ./hello_window.cpp :noweb yes
  #include <glad/glad.h>
  #include <GLFW/glfw3.h>
  #include <iostream>
  <<includes_plus>>

  <<declaration_resize_callback>>
  <<escape_window_declaration>>

  int main ()
  {
    glfwInit();
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    // glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE); <- Caso fosse MacOS

    <<window_options>>

    <<init_glad>>

    <<gl_viewport>>

    <<window_resize_callback_registration>>

    <<close_loop>>

    <<glfw_terminate>>
    
    return 0;
  }

  <<definition_resize_callback>>

#+end_src

 Nessa parte, configuramos o GLFW (para não termos que fazer isso na mão) com cada uma das opções (e deve ser um enum) e o valor da opção.

 Nesse caso, damos para ele a versão mais simples do OpenGL que falamos lá em cima, a 3.3.

#+name: window_options
#+begin_src C++ 
  GLFWwindow* window = glfwCreateWindow(800, 600, "LearnOpenGL", NULL, NULL);

  std::cout << "Creating window..." << std::endl; // Para termos um feedback

  if (window == NULL)
    {
      std::cout << "Failed to create GLFW window" << std::endl;
      glfwTerminate();
      return -1;
    }
  glfwMakeContextCurrent(window);
#+end_src

 Com uma largura e altura, respectivamente, e o nome, criamos a janela. Já que ela ainda não tem uma lógica de aguardar, então ela surge por um micro segundo e some, por isso damos um aviso no console.

 Precisamos inicializar o GLAD também, já que vamos usar ele para gerenciar ponteiros de funções.

#+name: init_glad
#+begin_src C++
  if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress))
    {
    std::cout << "Failed to initialize GLAD" << std::endl;
      return -1;
    }
#+end_src

 Para gerenciar o tamanho da tela (virtual, o /view port/), temos esse código aqui:

#+name: gl_viewport
#+begin_src C++
  glViewport(0, 0, 800, 600);
#+end_src

 É interessante que isso é o espaço que o OpenGL vai tomar da janela, então poderíamos dar para ele uma tela menor e fazer com que coisas apareçam na janela.

 Também há uma questão de que o OpenGL nos dá um jeito de fazer referência meio estranha, com o 0,0 sendo o meio da tela, com -1 mais a esquerda, e/ou mais a cima.

 Lembremos que é o sistema de coordenadas de tela.

 E caso queiramos ter uma janela que responde com o usuário mexendo nas dimensões dela, usamos isso aqui:

#+name: declaration_resize_callback
#+begin_src C++
  void framebuffer_size_callback(GLFWwindow* window, int width, int height);
#+end_src

 com a immplementação ficando:

#+name: definition_resize_callback
#+begin_src C++
  void framebuffer_size_callback(GLFWwindow* window, int width, int height)
  {
    glViewport(0, 0, width, height);
  }
#+end_src

 Agora, vai ser meio estranho, já que registramos o /callback/, mas não passamos argumentos para ele. Isso acontece pelo GLFW fazer isso pra gente:

#+name: window_resize_callback_registration
#+begin_src C++
  glfwSetFramebufferSizeCallback(window, framebuffer_size_callback);
#+end_src

 Finalmente, vamos colocar um /loop/ para ver se deve ou não fechar a janela:

#+name: close_loop
#+begin_src C++ :noweb yes
  while(!glfwWindowShouldClose(window))
    {
      <<escape_window_call>>

      <<cleaning_color_plus>>
        
      glfwSwapBuffers(window);
      glfwPollEvents();
    }
#+end_src

 Preste atenção que usamos o modelo de /double buffering/. Lembre-se: o da frente é a superfície de exibição, o de trás é onde o programa escreve.

 E, por fim, precisamos limpar a bagunça:

#+name: glfw_terminate
#+begin_src C++
  glfwTerminate();
#+end_src

 Queremos colocar um pouco de resposta a entradas no nosso programa, como, ao apertar ESC, fechar o programa:

#+name: escape_window_declaration
#+begin_src C++
  void processInput(GLFWwindow *window)
  {
    if(glfwGetKey(window, GLFW_KEY_ESCAPE) == GLFW_PRESS)
      glfwSetWindowShouldClose(window, true);
  }
#+end_src

#+name: escape_window_call
#+begin_src C++
  processInput(window);
#+end_src

 Aqui, eles falam que "o /render loop/ também é chamado de frame", mas eu nunca vi alguém além deles chamarem isso assim. Que seja, não seria a primeira vez deles fazendo besteira.

 Mas uma coisa que é legal é esse negócio aqui, que dá uma cor para a tela, mostrando que ela está se limpando:

#+name: cleaning_color
#+begin_src C++
  glClearColor(0.2f, 0.3f, 0.3f, 1.0f);
  glClear(GL_COLOR_BUFFER_BIT);
#+end_src

 E eles chamam a primeira função de /state setting/, com a segunda sendo /state using/. O que é bem maneiro, ter a distinção e o vocabulário.

 E por termos acabado, vamos fazer uma bagunça: e se as cores de limpeza mudarem com o tempo?

#+name: includes_plus
#+begin_src C++
  #include <cmath>
  #include <chrono>

  // e vamos fazer uma sujeirinha aqui:

  auto beginning_app = std::chrono::high_resolution_clock::now();
#+end_src

 E, então, vamos usar cosseno e tempo para brincar:

#+name: cleaning_color_plus
#+begin_src C++
  auto r = std::cosf(std::chrono::duration<float>(std::chrono::high_resolution_clock::now() - beginning_app).count()) + 1.0f;
  auto g = std::cosf(std::chrono::duration<float>(std::chrono::high_resolution_clock::now() - beginning_app).count()) + 1.0f;
  auto b = std::cosf(std::chrono::duration<float>(std::chrono::high_resolution_clock::now() - beginning_app).count()) + 1.0f;

  glClearColor(r, g, b, 1.0f);
  glClear(GL_COLOR_BUFFER_BIT);
#+end_src

Bem, eu acho que por termos perda de precisão, não varia tanto assim, mas que seja, ela pisca!

* Hello Triangle

 Uma parte razoável do problema dos gráficos é transforma 3D em 2D. Muitos dos trabalhos são paralelizáveis e são paralelizados. A GPU processa cada uma das etapas com programinhas, chamados de /shaders/. Para nós, a linguagem é a /OpenGL Shading Language/, ou /GLSL/.

 Cada tipo de /shader/ afeta uma parte diferente da /pipeline/:

 1) Começamos com dados de vértices;
 2) Podemos aplicar /shaders/ de vértices;
 3) Podemos aplicar /shaders/ de geometria;
 4) A forma é montada, com a geometria;
 5) A forma é rasterizada;
 6) Podemos aplicar /shaders/ de fragmentos, provenientes da rasterização;
 7) São feitos testes e misturas (/blending/).

 Só não conseguimos interferir com os passos 4, 5 e 7. Pelo menos, no OpenGL.

 Toda vez que chamamos as funções de desenho, podemmmos pedir para o OpenGL desenhar alguns primitivos, como src_c{GL_POINTS}, src_c{GL_TRIANGLES} e src_c{GL_LINE_STRIP}.

 Para cada etapa, somando um ao índice:
 1) Entram vértices individuais e saem vértices individuais, transformando as coordenadas e outros atributos;
 2) Opcional, mas quando tem, gera mais (ou remove) vértices para formar primitivos de vários jeitos. No caso de exemplo, gerar triângulos dada uma forma;
 3) Montam primitivos a partir dos vértices;
 4) Dos primitivos, acontece o /clipping/ para reduzir a quantidade de fragmentos que não seriam renderizados, e então, geramos fragmentos segundo o tamanho da tela;
 5) Calculamos, em geral, a cor do fragmento. Isso pode levar em conta iluminação, texturas, sombras e mais um monte de coisa;
 6) Por fim, acontece o /alpha testing/ e /blending/, que dá transparência, assim como alguns fragmentos podem ser descartados segundo estarem na frente ou atrás de um objeto.

 O OpenGL define isso tudo, exceto um /shader/ de vértice e de fragmento. Isso somos nós que decidimos.

 Não só isso, mas o programa só vai mostrar coisas que estiverem nas coordenadas normalizadas do dispositivo, as entre -1.0 e 1.0 nos três eixos (pensando no espaço tridimensional).
 
** O início do triângulo

 Então, já que queremos apenas um singelo triângulo, façamos seus vértices:

#+name: triangulo
#+begin_src C++
  float vertices[] = {
    -0.5f, -0.5f, 0.0f,
     0.5f, -0.5f, 0.0f,
     0.0f,  0.5f, 0.0f
  };
#+end_src

 Essas coordenadas são as de mundo, e para transformar, depois, para nossa tela, vamos usar a transformada de câmera (ou /viewport transform/).

 Bem, agora que temos o nosso triângulo, uma coisa de cada vez.

 Vamos ter que mandar esse cara para a placa de vídeo, já que é ela que vai ter que ler esses dados, interpretar segundo o /shader/ e continuar com a /pipeline/ daí.

 Como toda boa linguagem, vamos ter que gerenciar a memória na mão. Para essa primeira parte, temos o /vertex buffer object/ ou VBO, que guarda vértices.

 Criamos /buffers/ assim:

#+name: vbo
#+begin_src C++
  unsigned int VBO;
  glGenBuffers(1, &VBO);

  glBindBuffer(GL_ARRAY_BUFFER, VBO);

  glBufferData(GL_ARRAY_BUFFER, sizeof(vertices), vertices, GL_STATIC_DRAW);
#+end_src

 Aqui, ele gera o /buffer/, atribui a referência ao tipo GL_ARRAY_BUFFER e damso um tamanho para ele.

 Damos o tipo de dados para ele ali por escrevermos uma vez e ele ser usado várias vezes.

** O /vertex shader/

#+name: vertex_shader
#+begin_src glsl
  #version 330 core

  layout (location = 0) in vec3 aPos;

  void main()
  {
    gl_Position = vec4(aPos.x, aPos.y, aPos.z, 1.0);
  }
#+end_src

 Temos ali a versão, a declaração dos atributos (a explicar mais), com o ~main()~, que é o programa que dá a posição para cada vértice.

 No caso, a ~gl_Position~ toma um ~vec4~ por causa da /perspective division/, que é a última dimensão e vamos falar dela mais pra frente.

 Esse é o /shader/ mais simples possível por não mudar a geometria em absolutamente nada. Em geral, o mínimo que fazemos é a normalização das coordenadas.

 Vamos testar uma sapecagem aqui por causa do Emacs:

#+name: vertex_shader_source
#+begin_src C++ :noweb yes
  const char *vertexShaderSource = "<<vertex_shader>>";
#+end_src

 E então, precisamos criar o nosso /vertex shader object/:

#+name: vertex_shader_object
#+begin_src C++
  unsigned int vertexShader;

  vertexShader = glCreateShader(GL_VERTEX_SHADER);
#+end_src

 E mandar para o /driver/ compiler:

#+name: vertex_shader_compile
#+begin_src C++
  glShaderSource(vertexShader, 1, &vertexShaderSource, NULL);
  glCompileShader(vertexShader);
#+end_src

 E, para fins práticos, um trecho de código para ver se está tudo bem:

#+name: veretx_shader_error_handling
#+begin_src C++
  int success;
  char infoLog[512];
  glGetShaderiv(vertexShader, GL_COMPILE_STATUS, &success);

  if(!success){
    glGetShaderInfoLog(vertexShader, 512, NULL, infoLog);
    std::out << "ERROR::SHADER::VERTEX::COMPILATION_FAILED\n" << infoLog << std::endl;
   }
#+end_src

 Então, resumindo o que aconteceu aqui:
 1) Definimos o /shader/, o programa de fato;
 2) Vamos declarar ele como um /string/;
 3) Pedimos para o /driver/ criar e dar um identificados para ele;
 4) Conectamos o código do /shader/ com o identificador;
 5) Pedimos para compilar o /shader/ pelo identificador;
 6) Caso hajam erros, mande para a ~stdout~, se não, a vida que segue.

 Esse é meio que o padrão comum para todos os /shaders/. Meio chato, mas eis o estado de computação heterogênea.

** O /fragment shader/

 A última parte que precisamos acrescentar. Geralmente aqui é que bastante coisa acontece, já que é quando damos cor ou textura para as coisas, então é onde temos /feedback/ bem bom.

#+name: fragment_shader
#+begin_src glsl
  #version 330 core
  out vec4 FragColor;

  void main()
  {
    FragColor = vec4(1.0f, 0.5f, 0.2f, 1.0f);
  }
#+end_src

 Definimos ali um tipo de dado de saída e, pela sua simplicidade, ele só dá um valro fixo para a cor.

 Vamos fazer as mesmas coisas do /vertex/ para aqui:

#+name: fragment_shader_compile
#+begin_src C++
  unsigned int fragmentShader;
  fragmentShader = glCreateShader(GL_FRAGMENT_SHADER);
  glShaderSource(fragmentShader, 1, &fragmentShaderSource, NULL);
  glCompileShader(fragmentShader);
#+end_src

 E, para fins de teste, vamos combinar também a mesma questão de erros:

#+name: fragment_shader_error_handling
#+begin_src C++
  glGetShaderiv(fragmentShader, GL_COMPILE_STATUS, &success);

  if(!success)
   {
    glGetShaderInfoLog(fragmentShader, 512, NULL, infoLog);
    std::out << "ERROR::SHADER::FRAGMENT::COMPILATION_FAILED\n" << infoLog << std::endl;
   }
#+end_src

** O /shader program/

 Precisamos juntar (ligar, ou até /linkar/, alguns diriam) os programas em uma coisa só, que é ativada a cada chamada de desenho.

 É legal que ele te avisa se der problema, geralmente relacionado à saída de um programa não bater com a entrada do outro.

#+name: shader_linking
#+begin_src C++
  unsigned int shaderProgram;
  shaderProgram = glCreateProgram();

  glAttachShader(shaderProgram, vertexShader);
  glAttachShader(shaderProgram, fragmentShader);
  glLinkProgram(shaderProgram);
#+end_src

 Por fim, vamos verificar erros no programa também:

#+name: program_shader_error_handling
#+begin_src C++
  glGetProgramiv(shaderProgram, GL_LINK_STATUS, &success);
  if(!success) {
    glGetProgramInfoLog(shaderProgram, 512, NULL, infoLog);
    std::out << "ERROR::SHADER::PROGRAM::LINKING_FAILED\n" << infoLog << std::endl;
   }
#+end_src

 Por fim, vamos pedir para o /driver/ fazer a GPU usar o nosso programa e, então, limpar o que não precisamos (já que foi ligado e mandamos para a GPU):

#+name: program_shader_use
#+begin_src C++
  glUseProgram(shaderProgram);

  glDeleteShader(vertexShader);
  glDeleteShader(fragmentShader);
#+end_src
